on: [pull_request]

name: openapi-diff

jobs:
    openapi-compatiable:
        strategy:
            max-parallel: 1
            fail-fast: false
        runs-on: ubuntu-latest
        steps:
            - name: Check out HEAD revision
              uses: actions/checkout@v2
              with:
                  ref: ${{ github.head_ref }}
                  path: head
            - name: Check out BASE revision
              uses: actions/checkout@v2
              with:
                  ref: ${{ github.base_ref }}
                  path: base
            - name: Roda openapi-diff
              run: npx openapi-diff 'head/VTEX - Catalog API.json' 'base/VTEX - Catalog API.json'
